// utils/culturalKeywords.js
module.exports = [
    "vedic",
    "upanishads",
    "mahabharata",
    "ramayana",
    "ayurveda",
    "arthashastra",
    "bharat",
    "sanatan",
    "indus valley",
    "buddhism",
    "jainism",
    "temples",
    "ashoka",
    "gupta empire",
    "chola dynasty",
    "culture",
    "tradition",
    "rituals",
    "ancient india",
    "bharatiya",
    "yoga",
    "sanskrit",
    "scripture",
    "philosophy",
    "religion",
  ];
  